export enum Permisison {
    HANDLE_MENU = "HANDLE_MENU",
    HANDLE_CATEGORY = "HANDLE_CATEGORY",
    HANDLE_PRODUCT_TYPE = "HANDLE_PRODUCT_TYPE",
    HANDLE_PRODUCT = "HANDLE_PRODUCT",
    HANDLE_CHILD_PRODUCT = "HANDLE_CHILD_PRODUCT",
    HANDLE_ADMIN = "HANDLE_ADMIN",
  }